hostname_enabled_backends_enabled = false
enabled_backends = ["arch"]
hostname_groups_enabled = true

[hostname_groups]
kek = ["browsers"]
archlinux = ["system","office","music","mail","latex","emacs","dev","desktop-rofi","desktop-polybar","desktop-misc","desktop","console","browsers"]


[arch]
package_manager = "paru"
