arch = {
  packages = [
    "rsync",
    "bluetui",
    "bashmount",
    "pv",
    "man-db",
    "aria2",
    "openssl",
    "ncdu",
    "megacmd",
    "jless",
    "direnv",
    "git-lfs",
    "sshfs",
    "tokei",
    "unrar",
    "unzip",
    "zip",
    "pass",
    "7zip",
    "fzf",
    "neofetch",
    "nethogs",
    "htop",
    "eza",
    "ncurses",
    "bottom",
    "alacritty",
    "xclip",
    "tmuxp",
    "tmux",
    "starship",
    "nushell",
    "atuin",
    "shell-color-scripts-git",
    "fish",
    "xorg-xhost",
    "xorg-xrdb",
  ]
}
