arch = [
"android-file-transfer",
"remmina",
"noto-fonts-emoji",
"telegram-desktop",
"bluez",
"xorg-xev",
"gparted",
"gnome-disk-utility",
"anydesk-bin",
"qbittorrent",
"gnome-font-viewer",
"xdg-utils",
"thunar",
"copyq",
"feh",
"polkit-gnome",
"fontconfig",
"xorg-xmodmap",
"network-manager-applet",
"pavucontrol",
"light",
"arandr",
"xorg-xprop",
"xss-lock",
"xorg-xinit",]
