arch = [
"libaio",
"uv",
"dbeaver",
"rust",
"git",
"wireshark-qt",
"socat",
"python-build",
"python-virtualenv",
"python-pip",
"python",
"php",
"gource",
"git-lfs",
"make",
"hugo",
"libfaketime",
"lua",
"cmake",
"gcc",
"pkgconf",
"gopls",
"go",
"jdk21-openjdk",
"nodejs",
"git-filter-repo",
"libvirt",
"dnsmasq",
"qemu-full",
"virt-manager",
"postgresql",
"docker-compose",
"docker",
"pandoc-cli",
"micromamba-bin",]
