arch = [
"texinfo",
"the_silver_searcher",
"ripgrep",
"hledger",
"gnu-free-fonts",
"ttf-unifont",
"yt-dlp",
"mpv",
"python-youtube-transcript-api",
"rdrview",
"graphviz",
"python-isort",
"python-black",
"yapf",
"plantuml",
"difftastic",
"xkb-switch",
"emacs",]
