arch = {
  packages = [
    "texinfo",
    "the_silver_searcher",
    "ripgrep",
    "hledger",
    "rclone",
    "gnu-free-fonts",
    "ttf-unifont",
    "telegram-tdlib",
    "yt-dlp",
    "mpv",
    "python-youtube-transcript-api",
    "rdrview",
    "graphviz",
    "python-isort",
    "python-black",
    "yapf",
    "plantuml",
    "difftastic",
    "xkb-switch",
    "emacs",
  ]
}
