arch = [
"ttf-dejavu",
"ttf-ms-fonts",
"python-pygments",
"biber",
"texlab",
"texlive-xetex",
"texlive-publishers",
"texlive-pstricks",
"texlive-plaingeneric",
"texlive-pictures",
"texlive-metapost",
"texlive-mathscience",
"texlive-latexrecommended",
"texlive-latexextra",
"texlive-latex",
"texlive-humanities",
"texlive-games",
"texlive-formatsextra",
"texlive-fontutils",
"texlive-binextra",
"texlive-bibtexextra",
"texlive-basic",]
