arch = [
"drawio-desktop",
"zotero-bin",
"digikam",
"rocketchat-desktop",
"obs-studio",
"okular",
"inkscape",
"kdenlive",
"ffmpeg",
"krita",
"gimp",
"libreoffice-fresh",
"zathura-djvu",
"zathura-pdf-mupdf",
"zathura-ps",
"zathura",]
