flatpak = {
  packages = [
    "user:chat.rocket.RocketChat",
  ]
}
arch = {
  packages = [
    "playonlinux",
    "gnumeric",
    "drawio-desktop",
    "zotero-bin",
    "digikam",
    "obs-studio",
    "okular",
    "inkscape",
    "kdenlive",
    "ffmpeg",
    "krita",
    "gimp",
    "libreoffice-fresh",
    "zathura-djvu",
    "zathura-pdf-mupdf",
    "zathura-ps",
    "zathura",
  ]
}
