arch = [
"xf86-video-ati",
"xf86-video-amdgpu",
"vulkan-radeon",
"nvidia-utils",
"vulkan-intel",
"intel-media-driver",
"libva-intel-driver",
"zram-generator",
"yadm",
"wpa_supplicant",
"wireless_tools",
"wget",
"xterm",
"vim",
"smartmontools",
"pipewire-jack",
"pipewire-pulse",
"pipewire-alsa",
"pipewire-audio",
"pipewire",
"paru",
"pacman-contrib",
"openssh",
"metapac",
"nano",
"linux-firmware",
"linux",
"lightdm-gtk-greeter",
"lightdm",
"iwd",
"grub",
"decman",
"base-devel",
"base",]
