[database]
user = 'postgres'
password = 'localdbpass'
database = 'data'
host = 'postgres'
port = 5432

[general]
root = '@format {env[HOME]}/logs-sync'
hash_db = '@format {this.general.root}/hash.db'
temp_data_folder = '/tmp/sqrt-data'
cli_log = '@format {env[HOME]}/.local/share/sqrt-data/cli.log'

[sync]
log_file = '@format {this.general.root}/sync.log'
target = 'ssh://pavel@sqrtminusone.xyz//home/pavel/logs-sync'

[archive]
days = 31
timeout = 5

[mpd]
library_csv = '@format {this.general.root}/mpd/mpd_library.csv'
log_folder = '@format {this.general.root}/mpd/logs'

[waka]
api_key = 'dummy'
api_url = 'https://wakatime.com/api/v1'
schema = 'wakatime'

[aw]
last_updated = '@format {this.general.root}/aw_last_updated.json'
logs_folder = '@format {this.general.root}/aw'
types = ['afkstatus', 'currentwindow', 'web.tab.current', 'app.editor.activity']
api = 'http://localhost:5600/api'
schema = 'aw'
skip_afk_interval = '900'
skip_afk_apps = '^(zoom|mpv)$'
skip_afk_titles = '^(YouTube)$'
webtab_apps = '^(Nightly|firefox)$'
skip_urls = '^(moz-extension|about:blank)'

[aw.apps_convert]
Nightly = 'firefox'
Chromium-browser = 'Chromium'
unknown = 'Emacs' # EXWM

[google]
android_file = '@format {this.general.root}/google/android-history.json'
android_schema = 'android'

[vk]
author = 'Pavel Korytov'
schema = 'vk'

[sleep]
file = '@format {this.general.root}/sleep/sleep-export.csv'
schema = 'sleep'

[sleep.geos]
e3336012 = 'test'

[location]
list_csv = '@format {this.general.root}/csv/locations.csv'
tz_csv = '@format {this.general.root}/csv/loc_timezones.csv'
hostnames_csv = '@format {this.general.root}/csv/loc_hostnames.csv'
